### ISSUE TITLE
TODO and TMP strings usage ?

### ISSUE THREAD

**Issue by SheepDomination** [eyosido/GlobalSearch#1]
Hi, how do I use TODO and TMP strings ?

**Comment by eyosido** [comment]
You may just enter them in Frames or Comments in your graph and the plugin will find them when using the default TODO and TMP entries in GlobalSearch search bar (open the combo-box, they're at the end). They are regular strings, however their search is always case-sensitive.

**Comment by SheepDomination** [comment]
> You may just enter them in Frames or Comments in your graph and the plugin will find them when using the default TODO and TMP entries in GlobalSearch search bar (open the combo-box, they're at the end). They are regular strings, however their search is always case-sensitive.

At the beginning or end of a comment I would enter in TODO or TMP; as I tried this but nothing shows when listing all TODO in the search field for TODO for example ?

**Comment by eyosido** [comment]
The location where you enter the text is not important. Did you click on the Magnifying Glass button to start the search? Also make sure to hit the Refresh button (to the right of the search text field) so the plugin knows where to search.

![TODOSearchExample](https://github.com/eyosido/GlobalSearch/assets/104434968/68cd0e84-beb0-4cc1-bca7-5d9fab26dfea)

**Comment by SheepDomination** [comment]
Although there is no way to jump to the TODO or TMP nodes ?

**Comment by eyosido** [comment]
There is no way to jump to them unfortunately, this feature is not present in the Python API. However you can copy the text (right-click on the found entry) and paste it into the regular Search field of Designer, it will them show into your graph.

**Comment by SheepDomination** [comment]
> There is no way to jump to them unfortunately, this feature is not present in the Python API. However you can copy the text (right-click on the found entry) and paste it into the regular Search field of Designer, it will them show into your graph.

How about linking pins so that you can go to TMP or TODO and it will jump to that pin whether visible or not ?
